---
version: "3.7"
services:
  nginx-alpine:
    build:
      context: build/alpine
      dockerfile: Dockerfile
      args:
        alpine_ver: 3.17.2
        nginx-ver: 1.22.1
    environment:
        ALPINE_VERSION: 3.17.2
        NGINX_VERSION: 1.22.1
    image: jrpamid/nginx-alpine:1.22.1
  
  nginx-centos:
    build:
      context: build/centos
      dockerfile: Dockerfile
      args:
        nginx-ver: 1.22.1
        centos_ver: 8
    environment:
        NGINX_VERSION: 1.22.1
        NGINX_USER: nginx
        NGINX_PORT: 8080
    image: jrpamid/nginx-centos:1.22.1
 
  nginx-ubuntu:
    build:
      context: build/ubuntu
      dockerfile: Dockerfile
      args:
        ubuntu_codename: kinetic
        nginx-ver: 1.22.1
    environment:
       NGINX_USER: nginx
       NGINX_PORT: 8080
       NGINX_VERSION: 1.22.1
    image: jrpamid/nginx-ubuntu:1.22.1  

    
