---
version: "3.7"
services:
  nginx-alpine:
    build:
      context: build/alpine
      dockerfile: Dockerfile
      args:
        alpine_ver: 3.12
        nginx-ver: 1.18.0
    environment:
        ALPINE_VERSION: 3.12
        NGINX_VERSION: 1.18.0
    image: jrpamid/nginx-alpine:1.18.0
  
  nginx-centos:
    build:
      context: build/centos
      dockerfile: Dockerfile
      args:
        nginx-ver: 1.18.0
        centos_ver: 8
    environment:
        NGINX_VERSION: 1.18.0
        NGINX_USER: nginx
        NGINX_PORT: 8080
    image: jrpamid/nginx-centos:1.18.0
 
  nginx-ubuntu:
    build:
      context: build/ubuntu
      dockerfile: Dockerfile
      args:
        ubuntu_codename: disco
        nginx-ver: 1.18.0
    environment:
       NGINX_USER: nginx
       NGINX_PORT: 8080
       NGINX_VERSION: 1.18.0
    image: jrpamid/nginx-ubuntu:1.18.0  

    
