---
version: "3.7"
services:
  nginx_alpine:
    build:
      context: build/alpine
      dockerfile: Dockerfile
      args:
        alpine_ver: 3.10.3
        nginx_ver: 1.16.1
    environment:
        ALPINE_VERSION: 3.10.3
        NGINX_VERSION: 1.16.1
    image: jrpamid/nginx_alpine:1.16.1
  
  nginx_centos:
    build:
      context: build/centos
      dockerfile: Dockerfile
      args:
        nginx_ver: 1.16.1
    environment:
        NGINX_VERSION: 1.16.1
        NGINX_USER: nginx
        NGINX_PORT: 8080
    image: jrpamid/nginx_centos:1.16.1
 
  nginx_ubuntu:
    build:
      context: build/ubuntu
      dockerfile: Dockerfile
      args:
        ubuntu_codename: disco
    environment:
       NGINX_USER: nginx
       NGINX_PORT: 8080
    image: jrpamid/nginx_ubuntu:disco  

    
