  
name: Nginx on Ubuntu OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Nginx on ubuntu image
      run: |
       cd ./build/ubuntu
       echo "${{ secrets.DOCKERPW }}" | docker login -u "jrpamid" --password-stdin
       docker build -t jrpamid/nginx_ubuntu:1.18.0 --build-arg ubuntu_codename=xenial --build-arg nginx_ver=1.18.0 .
       docker push jrpamid/nginx_ubuntu:1.18.0
