name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Nginx on Alpine image
      run: |
       cd ./build/alpine  
       echo "${{ secrets.DOCKERPW }}" | docker login -u "jrpamid" --password-stdin
       docker build -t jrpamid/nginx_alpine:1.18.0 --build-arg alpine_ver=3.12 --build-arg nginx_ver=1.18.0 .
       docker push jrpamid/nginx_alpine:1.18.0
