name: Nginx on Alpine OS


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ALPINE_VERSION: 'latest'
  NGINX_VERSION: 1.22.1
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Nginx on Alpine image
      run: |
       cd ./build/alpine  
       echo "${{ secrets.DOCKERPW }}" | docker login -u "jrpamid" --password-stdin
       docker build -t jrpamid/nginx-alpine:${{ env.NGINX_VERSION }} --build-arg alpine_ver=${{ env.ALPINE_VERSION }} --build-arg nginx_ver=${{ env.NGINX_VERSION }} .
       docker push jrpamid/nginx-alpine:${{ env.NGINX_VERSION }}
