  
name: Nginx on CentOs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NGINX_VERSION: 1.22.1
  CENTOS_VERSION: 7
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Nginx on Centos image
      run: |
       cd ./build/centos
       echo "${{ secrets.DOCKERPW }}" | docker login -u "jrpamid" --password-stdin
       docker build -t jrpamid/nginx-centos:${{ env.NGINX_VERSION }} --build-arg centos_ver=${{ env.CENTOS_VERSION }} --build-arg nginx_ver=${{ env.NGINX_VERSION }} .
       docker push jrpamid/nginx-centos:${{ env.NGINX_VERSION }}
