  
name: Nginx on Ubuntu OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NGINX_VERSION: 1.22.1
  UBUNTU_CODENAME: "kinetic"
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Nginx on ubuntu image
      run: |
       cd ./build/ubuntu
       echo "${{ secrets.DOCKERPW }}" | docker login -u "jrpamid" --password-stdin
       docker build -t jrpamid/nginx-ubuntu:${{ env.NGINX_VERSION }} --build-arg ubuntu_codename=${{ env.UBUNTU_CODENAME }} --build-arg nginx_ver=${{ env.NGINX_VERSION }} .
       docker push jrpamid/nginx-ubuntu:${{ env.NGINX_VERSION }}
